name: ducamendes
favicon: null
layout_spectrum: 0.24972
typography_spectrum: 0.055495980428531766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8944255171809345
  lightness: 0.8332220576703548
  saturation: 0.7046710341237485
  rhythmicContrast: 0.5966505690012127
purpose: []
