name: ducamendes
favicon: null
layout_spectrum: 0.9029060371685773
typography_spectrum: 0.8189486071933061
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7279123491607606
  lightness: 0.24140033684670925
  saturation: 0.1963054125662893
  rhythmicContrast: 0.13617217354476452
purpose: []
