name: ducamendes
favicon: null
layout_spectrum: 0.24972
typography_spectrum: 0.055495980428531766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9cc100'
    - '#588600'
    - '#2a4a00'
    - '#eef198'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
