name: ducamendes
favicon: null
layout_spectrum: 0.49528
typography_spectrum: 0.18009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#06050a'
    - '#2c2c2c'
    - '#6586a5'
    - '#c0bfc4'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0
purpose: []
